server:
  port: 8887
spring:
  application:
    name: spring-cloud-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/emirgarip/user-post-app-configurations
##          uri: file:///Users/omer_garipagaoglu/IdeaProjects/local-git